"""Tests for Phase 1B enhancements: config constants, forecast metadata, new model fields."""
from datetime import date, timedelta
from decimal import Decimal

from warehouse_app.models.user import User
from warehouse_app.models.store import Store
from warehouse_app.models.inventory_item import InventoryItem
from warehouse_app.models.store_item_setting import StoreItemSetting
from warehouse_app.models.audit_log import AuditLog
from warehouse_app.models.replenishment_plan_line import ReplenishmentPlanLine


class TestConfigConstants:
    def test_config_has_usage_windows(self, app):
        assert app.config['DEFAULT_USAGE_WINDOW_SHORT'] == 7
        assert app.config['DEFAULT_USAGE_WINDOW_LONG'] == 14

    def test_config_has_csv_limits(self, app):
        assert app.config['CSV_MAX_ROWS'] == 10000
        assert app.config['CSV_MAX_QUANTITY'] == 999999

    def test_config_has_fulfillment_limits(self, app):
        assert app.config['BULK_UPDATE_MAX_LINES'] == 500
        assert app.config['PICKER_NOTE_MAX_LENGTH'] == 500

    def test_config_has_confidence_threshold(self, app):
        assert app.config['MIN_DATA_POINTS_HIGH_CONFIDENCE'] == 5


class TestNewModelFields:
    def test_user_last_login(self, db):
        user = User(full_name='Test', email='test_login@test.com', role='admin')
        user.set_password('pass')
        db.session.add(user)
        db.session.commit()

        assert user.last_login_at is None
        user.record_login()
        db.session.commit()
        assert user.last_login_at is not None

    def test_store_address_and_schedule(self, db):
        store = Store(name='Test', code='TST', address='123 Main St',
                      delivery_schedule='MWF', active=True)
        db.session.add(store)
        db.session.commit()
        assert store.address == '123 Main St'
        assert store.delivery_schedule == 'MWF'

    def test_item_description_and_storage(self, db):
        item = InventoryItem(
            item_name='Test Item', sku='TST-001', category='Test',
            description='A test item', storage_type='refrigerated',
            case_pack_quantity=6,
        )
        db.session.add(item)
        db.session.commit()
        assert item.description == 'A test item'
        assert item.storage_type == 'refrigerated'

    def test_setting_usage_window_days(self, db, sample_stores, sample_items):
        setting = StoreItemSetting(
            store_id=sample_stores[0].id, item_id=sample_items[0].id,
            par_level=10, safety_stock=2, rounding_rule='none',
            usage_window_days=5, active=True,
        )
        db.session.add(setting)
        db.session.commit()
        assert setting.usage_window_days == 5

    def test_audit_log_user_fk(self, db, admin_user):
        entry = AuditLog(
            entity_type='test', entity_id=1, action='test',
            changed_by_user_id=admin_user.id,
        )
        db.session.add(entry)
        db.session.commit()
        assert entry.changed_by_user is not None
        assert entry.changed_by_user.email == 'admin@test.com'


class TestForecastMetadata:
    def test_plan_lines_have_forecast_metadata(self, db, sample_plan):
        line = ReplenishmentPlanLine.query.filter_by(plan_id=sample_plan.id).first()
        # Lines generated by the recommendation engine should have forecast metadata
        assert line.forecast_avg_daily_usage is not None
        assert line.forecast_on_hand is not None
        assert line.forecast_target is not None
        assert line.forecast_window_days is not None

    def test_recommendation_returns_forecast_metadata(self, db, sample_stores, sample_items,
                                                       sample_settings, sample_usage, sample_snapshots):
        from warehouse_app.services.recommendation import calculate_recommendation
        store = sample_stores[0]
        item = sample_items[0]
        rec = calculate_recommendation(store.id, item.id, date.today())

        assert 'forecast_avg_daily_usage' in rec
        assert 'forecast_on_hand' in rec
        assert 'forecast_target' in rec
        assert 'forecast_window_days' in rec
        assert rec['forecast_avg_daily_usage'] >= 0
        assert rec['forecast_on_hand'] >= 0
        assert rec['forecast_target'] >= 0


class TestLastLoginTracking:
    def test_login_updates_last_login(self, client, admin_user, db):
        assert admin_user.last_login_at is None
        client.post('/auth/login', data={
            'email': 'admin@test.com', 'password': 'admin123',
        }, follow_redirects=True)
        db.session.refresh(admin_user)
        assert admin_user.last_login_at is not None


class TestCustomErrorHandlers:
    def test_404_html(self, admin_client):
        resp = admin_client.get('/nonexistent-page')
        assert resp.status_code == 404
        assert b'404' in resp.data

    def test_404_json(self, admin_client):
        resp = admin_client.get('/nonexistent-page',
                                 headers={'Accept': 'application/json'})
        assert resp.status_code == 404
        data = resp.get_json()
        assert data['error'] == 'Resource not found'
