"""phase1b_enhanced_models

Revision ID: 444493019ad2
Revises: ba14337f4d8c
Create Date: 2026-03-18 16:39:51.805507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444493019ad2'
down_revision = 'ba14337f4d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_changed_by_user_id'), ['changed_by_user_id'], unique=False)
        batch_op.create_foreign_key('fk_audit_logs_changed_by_user_id', 'users', ['changed_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('storage_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('replenishment_plan_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_avg_daily_usage', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('forecast_on_hand', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('forecast_target', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('forecast_window_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('store_item_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_window_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_schedule', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('delivery_schedule')
        batch_op.drop_column('address')

    with op.batch_alter_table('store_item_settings', schema=None) as batch_op:
        batch_op.drop_column('usage_window_days')

    with op.batch_alter_table('replenishment_plan_lines', schema=None) as batch_op:
        batch_op.drop_column('forecast_window_days')
        batch_op.drop_column('forecast_target')
        batch_op.drop_column('forecast_on_hand')
        batch_op.drop_column('forecast_avg_daily_usage')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('storage_type')
        batch_op.drop_column('description')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_changed_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_logs_changed_by_user_id'))

    # ### end Alembic commands ###
