"""initial models

Revision ID: ba14337f4d8c
Revises: 
Create Date: 2026-03-18 03:22:08.163874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba14337f4d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('case_pack_quantity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('case_pack_quantity > 0', name='ck_inventory_items_case_pack_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_sku'), ['sku'], unique=True)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'warehouse')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity_used >= 0', name='ck_daily_usage_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'item_id', 'usage_date', name='uq_daily_usage_store_item_date')
    )
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_usage_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_usage_usage_date'), ['usage_date'], unique=False)

    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_snapshot_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'item_id', 'snapshot_date', name='uq_inventory_snapshot_store_item_date')
    )
    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_store_id'), ['store_id'], unique=False)

    op.create_table('replenishment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'in_progress', 'completed')", name='ck_replenishment_plans_status'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replenishment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replenishment_plans_plan_date'), ['plan_date'], unique=True)

    op.create_table('store_item_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('par_level', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_send_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rounding_rule', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("rounding_rule IN ('none', 'round_up_integer', 'round_up_case_pack')", name='ck_store_item_settings_rounding_rule'),
    sa.CheckConstraint('min_send_quantity >= 0', name='ck_store_item_settings_min_send_quantity'),
    sa.CheckConstraint('par_level >= 0', name='ck_store_item_settings_par_level'),
    sa.CheckConstraint('reorder_threshold >= 0', name='ck_store_item_settings_reorder_threshold'),
    sa.CheckConstraint('safety_stock >= 0', name='ck_store_item_settings_safety_stock'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'item_id', name='uq_store_item_settings_store_item')
    )
    with op.batch_alter_table('store_item_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_item_settings_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_item_settings_store_id'), ['store_id'], unique=False)

    op.create_table('replenishment_plan_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('recommended_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('warning_flags', sa.JSON(), nullable=False),
    sa.Column('picker_note', sa.Text(), nullable=True),
    sa.Column('last_status_change_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confidence_level IN ('high', 'medium', 'low')", name='ck_plan_line_confidence'),
    sa.CheckConstraint("status IN ('pending', 'picked', 'loaded', 'delivered', 'shorted')", name='ck_plan_line_status'),
    sa.CheckConstraint('recommended_quantity >= 0', name='ck_plan_line_recommended_qty'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['replenishment_plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'store_id', 'item_id', name='uq_plan_line_plan_store_item')
    )
    with op.batch_alter_table('replenishment_plan_lines', schema=None) as batch_op:
        batch_op.create_index('ix_plan_lines_plan_status', ['plan_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_plan_lines_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_plan_lines_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_plan_lines_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replenishment_plan_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replenishment_plan_lines_store_id'))
        batch_op.drop_index(batch_op.f('ix_replenishment_plan_lines_plan_id'))
        batch_op.drop_index(batch_op.f('ix_replenishment_plan_lines_item_id'))
        batch_op.drop_index('ix_plan_lines_plan_status')

    op.drop_table('replenishment_plan_lines')
    with op.batch_alter_table('store_item_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_item_settings_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_item_settings_item_id'))

    op.drop_table('store_item_settings')
    with op.batch_alter_table('replenishment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replenishment_plans_plan_date'))

    op.drop_table('replenishment_plans')
    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_item_id'))

    op.drop_table('inventory_snapshots')
    with op.batch_alter_table('daily_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_usage_usage_date'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_store_id'))
        batch_op.drop_index(batch_op.f('ix_daily_usage_item_id'))

    op.drop_table('daily_usage')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_code'))

    op.drop_table('stores')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_sku'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
