"""Add actual_orders table for store order tracking

Revision ID: c65d1663d116
Revises: dd7ef6566eab
Create Date: 2026-03-20 14:23:19.702379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65d1663d116'
down_revision = 'dd7ef6566eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity_ordered >= 0', name='ck_actual_order_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'item_id', 'order_date', name='uq_actual_order_store_item_date')
    )
    with op.batch_alter_table('actual_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actual_orders_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actual_orders_order_date'), ['order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_actual_orders_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actual_orders_store_id'))
        batch_op.drop_index(batch_op.f('ix_actual_orders_order_date'))
        batch_op.drop_index(batch_op.f('ix_actual_orders_item_id'))

    op.drop_table('actual_orders')
    # ### end Alembic commands ###
