"""add forecast_method to plan lines

Revision ID: dd7ef6566eab
Revises: 444493019ad2
Create Date: 2026-03-19 03:59:53.779917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7ef6566eab'
down_revision = '444493019ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replenishment_plan_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_method', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replenishment_plan_lines', schema=None) as batch_op:
        batch_op.drop_column('forecast_method')

    # ### end Alembic commands ###
